alias acrtest='az login && az acr login --name acstest'
alias aksgo='echo "Using go ${GO_VERSION}" && alias go=go${GO_VERSION}'
alias gowork='aksgo && cd ${GOPATH}'
alias gorp='gowork && cd src/goms.io/aks/rp'
alias idweb='kinit THGAMBLE@NORTHAMERICA.CORP.MICROSOFT.COM && open -a safari https://idweb/'
alias aksdev='~/go/src/goms.io/aks/rp/bin/aksdev'
alias startdev='devboxsub && open -a "Azure VPN Client" && az vm start --name tg-202308 --resource-group thgamble-devbox && ssh devbox'
alias devboxsub='az login && az account set -s c1089427-83d3-4286-9f35-5af546a6eb67'
alias devsub='az account set -s d0ecd0d2-779b-4fd0-8f04-d46d07f05703'
