alias acrtest='az login && az acr login --name acstest'
alias gowork='cd ${GOPATH}'
alias gorp='gowork && cd src/goms.io/aks/rp'
alias idweb='kinit THGAMBLE@NORTHAMERICA.CORP.MICROSOFT.COM && open -a safari https://idweb/'
alias aksdev='~/go/src/goms.io/aks/rp/bin/aksdev'
alias startdev='open -a "Azure VPN Client" && ssh devbox'
alias devsub='az account set -s d0ecd0d2-779b-4fd0-8f04-d46d07f05703'
