#!/usr/bin/env bash
#
#
# Run all dotfiles installers.

cd "$(dirname $0)"/..

mac () {
   if test ! $(which brew)
   then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
   fi

   echo "-----------------------"
   echo "> updating with homebrew"
   brew bundle --file=./macos/brewfile
   brew update
   brew upgrade
   brew cleanup
   brew bundle dump --all --force --file=./tmp/brewfile
   echo "-----------------------"

   # find the installers and run them iteratively
   find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
}

linux () {
    RED="\033[1;31m"
    GREEN="\033[1;32m"
    NOCOLOR="\033[0m"
    echo "-----------------------"
    echo "> updating with apt"
    sudo apt update && \
    sudo apt install -y $(cat ./linux/aptfile)
    sudo apt upgrade && \
    sudo apt autoremove && \
    sudo apt autoclean && \
    apt-mark showmanual | sort -u > ./tmp/aptfile
    APTDIF=$(comm -23 ./tmp/aptfile ./linux/aptfile)
    echo -e "${RED}Unsaved packages: \n${APTDIF}${NOCOLOR}"
    echo "-----------------------"
    
    # find the installers and run them iteratively
    find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
}

if [ "$(uname)" == "Darwin" ]; then
    mac        
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    linux
fi

# case "$OSTYPE" in
#   darwin*)  echo "Bootstrapping OSX" ;; 
#   linux*)   linux_prep ;;
#   bsd*)     echo "BSD" ;;
#   msys*)    echo "WINDOWS" ;;
#   cygwin*)  echo "ALSO WINDOWS" ;;
#   *)        echo "unknown: $OSTYPE" ;;
# esac



