#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

echo "-----------------------"
sudo apt update
sudo apt upgrade -y
cat packages.txt | xargs sudo apt-get install -y
sudo apt autoremove -y
echo "-----------------------"

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
