#!/bin/bash


# could add this - xset dpms force off; sleep 2; xset dpms force on


#xrandr | grep ' connected'
#https://askubuntu.com/a/1427781
# /usr/lib/pm-utils/sleep.d/99_external_monitor_wake

DISPLAY=:1; export DISPLAY

case "$1" in
    suspend | hibernate | pre)
        # no operation
        :
        ;;
    resume | thaw | post)
        # wakes the external monitor connected to the HDMI port
        xrandr --output DP-4 --auto --right-of eDP-1 --primary
        sleep 3
        xrandr --output DP-4 --auto --right-of eDP-1 --primary
        ;;
esac

exit 0
